### ISSUE TITLE
Example with nwb-sass?

### ISSUE THREAD

**Issue by rafegoldberg** [how-to-react/nwb-styleguidist#1]
Hey y'all, great tip re: the `create-nwb-webpack-config` module! I was wondering if you might know how to extend this to support the [**nwb-sass** plugin](https://github.com/insin/nwb-sass)? Right now I have said plugin installed and working with NWB so that I can `import './style.scss'` in one of my components. But when I try to run the Styleguidist build I get the following error: 

```
Building style guide...
./src/components/A/style.scss 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> .ComponentA {
|   color: red;
| }
 @ ./src/components/A/index.js 11:0-22
```

Not sure if there's a configuration step I'm missing, or something? Any further tips would be appreciated!

**Comment by stephenwf** [comment]
The `nwb-sass` plugin itself only adds the following to your NWB config:
```
cssPreprocessors: {
    sass: {
      test: /\.s[ac]ss$/,
      loader: require.resolve('sass-loader'),
      defaultConfig: 'sassLoader'
    }
  }
```
so you could try adding this to your `nwb.config.js` yourself. That should then be picked up by the `create-nwb-webpack-config`. Although I've not tested with the latest NWB versions, so your milage may vary!

If you continue running into issues, Ill create a new repo with a minimal setup for styleguidist + sass

**Comment by rafegoldberg** [comment]
Thanks for the quick response @stephenwf! Will try that out.

**Comment by rafegoldberg** [comment]
So I tried adding that snippet directly to my NWB config to no avail. (NWB compilation continue to work, but Styleguidist still throws that "Module Parse Failed" error on build...) I inspected the returned Webpack config in my `styleguide.config.js` and it does indeed look like it's somehow missing the `/\.s[ca]ss$/` loader rules.

**Comment by stephenwf** [comment]
I'll take a look and see what I can find 👍

**Comment by stephenwf** [comment]
Had to do a few things to get it to work. 

First was install sass-loader (v7 specifically)

```
npm install sass-loader@^7 --dev
```

And then push the loader into the config:
```js
var createNwbWebpackConfig = require('create-nwb-webpack-config');

var config = createNwbWebpackConfig();

config.module.rules.push({
  test: /\.s[ac]ss$/,
  use: ['css-loader', 'sass-loader'],
});

module.exports = {
  webpackConfig: config,
  components: 'src/**/[A-Z]*.js'
};
```

Not ideal, but it did compile correctly afterwards!

**Comment by stephenwf** [comment]
Added branch: https://github.com/how-to-react/nwb-styleguidist/tree/with-sass

With another commit with the changes required: https://github.com/how-to-react/nwb-styleguidist/commit/01bd8da0688dd513aee7bd6c95b25a31a6c88d0e

**Comment by rafegoldberg** [comment]
@stephenwf I had to install `node-sass` as well as the `sass-loader@^7` dependency, but then it worked like a charm. really appreciate the help! (I do wonder if this has something to do with the way [NWB's "invisible" plugin implementation](https://github.com/insin/nwb/blob/master/docs/ImplementingPlugins.md#implementing-plugins) affects [`create-nwb-webpack-config`](https://github.com/stephenwf/create-nwb-webpack-config)?)

**Comment by stephenwf** [comment]
Yes, I think that's right. It must not be something that the `create-nwb-webpack-config` takes into account. To be honest, it's probably clearer to just add it in directly into the configuration, save some headaches next time you go to look at the config!
